name: Update Real Estate Data

on:
  # Run every Monday at 2 AM UTC (5 AM Israel time)
  schedule:
    - cron: '0 2 * * 1'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Run data aggregation script
        run: |
          cd ${{ github.workspace }}
          python3 scripts/data-scrapers/aggregate_data.py
      
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet public/data/community_data.json; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/data/community_data.json
          git add data/community_data_backup_*.json
          git commit -m "chore: Update real estate data - $(date +'%Y-%m-%d')"
          git push
      
      - name: No changes detected
        if: steps.check_changes.outputs.has_changes == 'false'
        run: |
          echo "No changes detected in community data. Skipping commit."
      
      - name: Summary
        run: |
          echo "### Data Update Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Timestamp:** $(date +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          echo "- **Status:** ${{ steps.check_changes.outputs.has_changes == 'true' && 'Updated' || 'No changes' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Data Sources:** Yad2, Madlan, Numbeo" >> $GITHUB_STEP_SUMMARY
          echo "- **Cities Updated:** 5 (Beit Shemesh, Modi'in, Rehovot, Netanya, Haifa)" >> $GITHUB_STEP_SUMMARY

